fix(prefix): remove ui prefix
funda-frontend/tailwind-config pull request #2
Opened 2020-11-05 14:24 UTC by bartderijk

As discussed on the bi-weekly VCL meeting, we agreed on removing the `ui-` prefix.

2020-11-05 14:53 UTC, dine submitted a review, later dismissed

2020-11-05 14:56 UTC, sukalas-a submitted a review, later dismissed

2020-11-05 15:03 UTC, dine approved these changes

2020-11-05 15:05 UTC, dine requested changes
Can you remove this file too? https://github.com/funda-frontend/tailwind-config/blob/master/.github/workflows/main.yml

2020-11-06 09:04 UTC, bartderijk commented
> Can you remove this file too? https://github.com/funda-frontend/tailwind-config/blob/master/.github/workflows/main.yml

Done!

2020-11-06 09:36 UTC, dine approved these changes

2020-11-06 09:37 UTC, merged